Traceback (most recent call last):
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ranit/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ranit/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Install StarDist and dependencies (run once)
!pip install stardist csbdeep

# Imports
from stardist.models import StarDist2D
from csbdeep.utils import normalize
from skimage.io import imread, imshow
import matplotlib.pyplot as plt
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m~/anaconda3/lib/python3.11/site-packages/csbdeep/models/__init__.py:5[0m
[1;32m      4[0m [38;5;28;01mtry[39;00m:
[0;32m----> 5[0m     [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mtensorflow[39;00m
[1;32m      6[0m     [38;5;28;01mdel[39;00m tensorflow

[0;31mModuleNotFoundError[0m: No module named 'tensorflow'

The above exception was the direct cause of the following exception:

[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[1], line 5[0m
[1;32m      2[0m get_ipython()[38;5;241m.[39msystem([38;5;124m'[39m[38;5;124mpip install stardist csbdeep[39m[38;5;124m'[39m)
[1;32m      4[0m [38;5;66;03m# Imports[39;00m
[0;32m----> 5[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mstardist[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmodels[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m StarDist2D
[1;32m      6[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mcsbdeep[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m normalize
[1;32m      7[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mskimage[39;00m[38;5;21;01m.[39;00m[38;5;21;01mio[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m imread, imshow

File [0;32m~/anaconda3/lib/python3.11/site-packages/stardist/models/__init__.py:3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m__future__[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m absolute_import, print_function
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mmodel2d[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Config2D, StarDist2D, StarDistData2D
[1;32m      4[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mmodel3d[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Config3D, StarDist3D, StarDistData3D
[1;32m      6[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mcsbdeep[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m backend_channels_last

File [0;32m~/anaconda3/lib/python3.11/site-packages/stardist/models/model2d.py:8[0m
[1;32m      5[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mmath[39;00m
[1;32m      6[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mtqdm[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m tqdm
[0;32m----> 8[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mcsbdeep[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmodels[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m BaseConfig
[1;32m      9[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mcsbdeep[39;00m[38;5;21;01m.[39;00m[38;5;21;01minternals[39;00m[38;5;21;01m.[39;00m[38;5;21;01mblocks[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m unet_block
[1;32m     10[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mcsbdeep[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m _raise, backend_channels_last, axes_check_and_normalize, axes_dict

File [0;32m~/anaconda3/lib/python3.11/site-packages/csbdeep/models/__init__.py:9[0m
[1;32m      7[0m [38;5;28;01mexcept[39;00m [38;5;167;01mModuleNotFoundError[39;00m [38;5;28;01mas[39;00m e:
[1;32m      8[0m     [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01msix[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m raise_from
[0;32m----> 9[0m     raise_from([38;5;167;01mRuntimeError[39;00m([38;5;124m'[39m[38;5;124mPlease install TensorFlow: https://www.tensorflow.org/install/[39m[38;5;124m'[39m), e)
[1;32m     12[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mtensorflow[39;00m[38;5;241m,[39m[38;5;250m [39m[38;5;21;01msys[39;00m
[1;32m     13[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtf[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m keras_import, IS_TF_1, BACKEND [38;5;28;01mas[39;00m K

File [0;32m<string>:3[0m, in [0;36mraise_from[0;34m(value, from_value)[0m

[0;31mRuntimeError[0m: Please install TensorFlow: https://www.tensorflow.org/install/
RuntimeError: Please install TensorFlow: https://www.tensorflow.org/install/

